# Generated by Django 4.2.7 on 2023-12-18 15:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dołączenia')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], default='individual', max_length=255, verbose_name='Typ użytkownika')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'ordering': ('-date_joined',),
            },
        ),
    ]
