# Generated by Django 4.2.7 on 2023-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], default='normal', max_length=255, verbose_name='Typ użytkownika'),
        ),
    ]
