# Generated by Django 4.2.7 on 2023-12-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
