# Generated by Django 4.2.7 on 2023-12-18 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('position', models.CharField(choices=[('BR', 'Bramkarz'), ('OB', 'Obrońca'), ('PO', 'Pomocnik'), ('NA', 'Napastnik')], max_length=2, verbose_name='Pozycja')),
                ('status', models.CharField(choices=[('aktywny', 'Aktywny'), ('nieaktywny', 'Nieaktywny')], max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Zdjęcie')),
            ],
        ),
    ]
