# Generated by Django 4.2.7 on 2023-12-22 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('type', models.CharField(choices=[('GW', 'Główny'), ('AS', 'Asystent')], max_length=2, verbose_name='Pozycja')),
                ('status', models.CharField(choices=[('aktywny', 'Aktywny'), ('nieaktywny', 'Nieaktywny')], max_length=20, verbose_name='Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Zdjęcie')),
                ('drużyna', models.CharField(blank=True, max_length=4, null=True, verbose_name='Drużyna')),
            ],
        ),
    ]
