# Generated by Django 4.2.7 on 2023-12-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='drużyna',
            new_name='team',
        ),
    ]
