# Generated by Django 4.2.7 on 2023-12-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_drużyna_coach_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='type',
            field=models.CharField(choices=[('GW', 'Główny'), ('AS', 'Asystent')], max_length=2, verbose_name='Rola'),
        ),
    ]
